

CREATE USER sysadm01 WITH PASSWORD 'adm123#';

GRANT SELECT, INSERT, DELETE, UPDATE ON INFO_PRODUCT TO sysadm01;
GRANT SELECT ON INFO_ORDER TO sysadm01;
GRANT SELECT, UPDATE ON ACCOUNT_LOGIN TO sysadm01;
GRANT SELECT, UPDATE ON SESSION_LOGIN TO sysadm01;
GRANT SELECT, UPDATE ON STATUS_LOGIN TO sysadm01;
GRANT EXECUTE ON FUNCTION sp_login(VARCHAR, VARCHAR) TO sysadm01;
GRANT EXECUTE ON FUNCTION sp_getpass(VARCHAR, VARCHAR, TIMESTAMP) TO sysadm01;


CREATE USER syscus02 WITH PASSWORD 'cus123#';

GRANT EXECUTE ON FUNCTION sp_login(VARCHAR, VARCHAR) TO syscus02;
GRANT EXECUTE ON FUNCTION sp_getpass(VARCHAR, VARCHAR, TIMESTAMP) TO syscus02;
GRANT SELECT ON INFO_PRODUCT TO syscus02;
GRANT SELECT, INSERT ON INFO_ORDER TO syscus02;
GRANT SELECT, INSERT, DELETE, UPDATE ON CART TO syscus02;
GRANT SELECT, INSERT, DELETE, UPDATE ON PROFILE_USER TO syscus02;
GRANT SELECT, INSERT, UPDATE ON ACCOUNT_LOGIN TO syscus02;
GRANT SELECT, INSERT, UPDATE ON SESSION_LOGIN TO syscus02;
GRANT SELECT, INSERT, UPDATE ON STATUS_LOGIN TO syscus02;
GRANT SELECT ON STATUS_ORDER TO syscus02;
GRANT SELECT ON CARD_PAY TO syscus02;